#!/bin/bash

# Docker registry credentials
DOCKER_USERNAME="rayen1doud1"
DOCKER_PASSWORD="123578951rayen"

# Log in to Docker registry
echo "Logging in to Docker registry..."
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


# Extract the container name of the running container with the specified planning_db image
container_name=$(docker ps --filter "ancestor=rayen1doud1/planning_db:latest" --format "{{.Names}}")

# Check if the container name was found
if [ -z "$container_name" ]; then
  echo "No running container found with the image rayen1doud1/planning_db:latest"
  exit 1
fi

# Extract the container ID of the running container with the task image
task_container_id=$(docker ps --filter "ancestor=rayen1doud1/task:latest" --format "{{.ID}}")

# Stop the running container for the task image if found
if [ -n "$task_container_id" ]; then
  echo "Stopping the running container for rayen1doud1/task:latest..."
  docker stop "$task_container_id"
fi

# Pull the latest task image
docker pull rayen1doud1/task:latest

# Run the Docker command with the extracted container name replacing 'database_name'
docker run --network my-network -d -p 8083:8083 -e SPRING_DATASOURCE_URL=jdbc:mysql://$container_name:3306/order_service rayen1doud1/task:latest
